---
title: "ADNI2 sample"
author: "Nathalie Fadel"
date: "3/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sqldf)
library(viridis)
library(kableExtra)
library(patchwork)
```

##Scan QC filter
```{r,  include=FALSE}
ad_bl <- read_csv("ADNI2_AD_SC_BL_3_22_2019_ALL.csv") %>%
  janitor::clean_names()

cn_bl <- read_csv("ADNI2_CN_SC_BL_3_22_2019.csv") %>%
  janitor::clean_names()
```

```{r,  include=FALSE}
filter(ad_bl, description == "MT1; GradWarp; N3m") %>%
  group_by(subject) %>%
  summarize(n()) %>%
  count() %>%
  knitr::kable()
#total subjects for AD group with correct image type

missing_MRI <- sqldf("SELECT subject FROM (SELECT subject FROM cn_bl WHERE modality = 'PET') WHERE subject NOT IN (SELECT subject FROM cn_bl WHERE modality = 'MRI')")

missing_MRI
#need to find which subjects in CN group *doesnt* have a MT1 MRI

```

##Descriptive statistics of sample

###Load sample dataset
```{r}
ad_sample <- read_csv("ADNI2_AD_SC_BL_3_26_2019.csv") %>%
  janitor::clean_names()

cn_sample <- read_csv("ADNI2_CN_SC_BL_3_30_2019.csv") %>%
  janitor::clean_names()

##AMENDED DATASET AFTER BSMAC-AIDED QC:
new_sample <- read_delim("20190405_ADNI_Scans_2_1.txt", delim = " ")
```

###Gender breakdown
```{r}
gender_ad = 
  new_sample %>%
  filter(group == "AD") %>%
  group_by(sex) %>%
  count() %>%
  rename(gender = sex) %>%
  knitr::kable() %>%
  kable_styling("striped", full_width = F) %>%
  add_header_above(c("Alzheimer's group" = 2))

gender_cn = 
  new_sample %>%
  filter(group == "CN") %>%
  group_by(sex) %>%
  count() %>%
  rename(gender = sex) %>%
  knitr::kable() %>%
  kable_styling("striped", full_width = F) %>%
  add_header_above(c("Cognitively normal group" = 2))

gender_ad
gender_cn

new_sample %>%
  filter(group == "AD") %>%
  group_by(sex) %>%
  ggplot(aes(x = sex), fill = sex) +
  geom_bar(fill = "purple4") +
  labs(x = "Gender", caption = "Gender distribution of subjects in Alzheimer's group")

new_sample %>%
  filter(group == "CN") %>%
  group_by(sex) %>%
  ggplot(aes(x = sex)) +
  geom_bar(fill = "mediumpurple1") +
  labs(x = "Gender", caption = "Gender distribution of subjects in cognitively normal group")

```

###Age distribution by disease group
```{r}
new_sample %>%
  filter(group == "AD") %>%
  group_by(age) %>%
  summarize(n()) %>%
  count()
#27-year age span
new_sample %>%
  filter(group == "AD") %>%
  summarize(min(age), max(age))
#56 to 89 years old for Alzheimer's group

new_sample %>%
  filter(group == "CN") %>%
  group_by(age) %>%
  summarize(n()) %>%
  count()
#27-year age span
new_sample %>%
  filter(group == "CN") %>%
  summarize(min(age), max(age))
#57 to 89 years old for CN group

new_sample %>%
  filter(group == "AD") %>%
  group_by(age) %>%
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 1, fill = "blue4", col = "black") +
  theme(axis.text.x = element_text(hjust=1)) +
  labs(x = "Age", caption = "Age distribution of subjects in Alzheimer's group") +
  scale_x_continuous(breaks = c(55, 60, 65, 70, 75, 80, 85, 90))

new_sample %>%
  filter(group == "CN") %>%
  group_by(age) %>%
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 1, fill = "lightskyblue", col = "black") +
  theme(axis.text.x = element_text(hjust=1)) +
  labs(x = "Age", caption = "Age distribution of subjects in cognitively normal group") +
  scale_x_continuous(breaks = c(55, 60, 65, 70, 75, 80, 85, 90))

```